In [3]:
import numpy as np
import matplotlib.pyplot as plt
import pandas as pd


In [4]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:13].values
y = dataset.iloc[:, 13].values

In [10]:
from sklearn.preprocessing import LabelEncoder, OneHotEncoder
labelencoder_X_1 = LabelEncoder()
X[:, 1] = labelencoder_X_1.fit_transform(X[:, 1])
labelencoder_X_2 = LabelEncoder()
X[:, 2] = labelencoder_X_2.fit_transform(X[:, 2])
onehotencoder = OneHotEncoder(categorical_features = [1])
X = onehotencoder.fit_transform(X).toarray()
X = X[:, 1:]

In [12]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X_train = sc.fit_transform(X_train)
X_test = sc.transform(X_test)

In [15]:
import keras
from keras.models import Sequential
from keras.layers import Dense

In [16]:
# Initialising the ANN
classifier = Sequential()

In [17]:
# Adding the input layer and the first hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu', input_dim = 11))

In [18]:
# Adding the second hidden layer
classifier.add(Dense(units = 6, kernel_initializer = 'uniform', activation = 'relu'))

In [19]:
# Adding the output layer
classifier.add(Dense(units = 1, kernel_initializer = 'uniform', activation = 'sigmoid'))

In [21]:
# Compiling the ANN
classifier.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])

In [22]:
# Fitting the ANN to the Training set
classifier.fit(X_train, y_train, batch_size = 10, epochs = 100)


Epoch 1/100
8000/8000 [==============================] - 5s 571us/step - loss: 0.4759 - acc: 0.7960
Epoch 2/100
8000/8000 [==============================] - 1s 142us/step - loss: 0.4258 - acc: 0.7960
Epoch 3/100
8000/8000 [==============================] - 1s 130us/step - loss: 0.4201 - acc: 0.8125
Epoch 4/100
8000/8000 [==============================] - 1s 127us/step - loss: 0.4174 - acc: 0.8270
Epoch 5/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4151 - acc: 0.8302
Epoch 6/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4135 - acc: 0.8302
Epoch 7/100
8000/8000 [==============================] - 1s 117us/step - loss: 0.4122 - acc: 0.8334
Epoch 8/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4112 - acc: 0.8341
Epoch 9/100
8000/8000 [==============================] - 1s 116us/step - loss: 0.4101 - acc: 0.8344
Epoch 10/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4091 - acc: 0.8356

8000/8000 [==============================] - 1s 125us/step - loss: 0.4002 - acc: 0.8359
Epoch 83/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4002 - acc: 0.8352
Epoch 84/100
8000/8000 [==============================] - 1s 123us/step - loss: 0.4005 - acc: 0.8349
Epoch 85/100
8000/8000 [==============================] - 1s 129us/step - loss: 0.4007 - acc: 0.8345
Epoch 86/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4005 - acc: 0.8349
Epoch 87/100
8000/8000 [==============================] - 1s 125us/step - loss: 0.4004 - acc: 0.8355
Epoch 88/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.3997 - acc: 0.8350
Epoch 89/100
8000/8000 [==============================] - 1s 124us/step - loss: 0.4001 - acc: 0.8345
Epoch 90/100
8000/8000 [==============================] - 1s 126us/step - loss: 0.4004 - acc: 0.8330
Epoch 91/100
8000/8000 [==============================] - 1s 128us/step - loss: 0.4005 - acc: 0.8354
Epo

In [26]:
# Predicting the Test set results
y_pred = classifier.predict(X_test)
y_pred = (y_pred > 0.5)
y_pred

array([[False],
       [False],
       [False],
       ...,
       [False],
       [False],
       [False]])

In [29]:

# Making the Confusion Matrix
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
cm

array([[1536,   59],
       [ 256,  149]], dtype=int64)

In [30]:
# Predicting a single new observation
"""Predict if the customer with the following informations will leave the bank:
Geography: France
Credit Score: 600
Gender: Male
Age: 40
Tenure: 3
Balance: 60000
Number of Products: 2
Has Credit Card: Yes
Is Active Member: Yes
Estimated Salary: 50000"""
new_prediction = classifier.predict(sc.transform(np.array([[0.0, 0, 600, 1, 40, 3, 60000, 2, 1, 1, 50000]])))
new_prediction = (new_prediction > 0.5)

In [39]:
new_prediction #THE CUSTOMER WILL NOT STAY IN THE BANK

array([[False]])

array([[False]])